// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADpQakK3gb8w1G_CLXY3D-G9HnO8BW8u8',
    appId: '1:967214662804:web:e5a035a794dc53ff71e081',
    messagingSenderId: '967214662804',
    projectId: 'pizza-suwalki421',
    authDomain: 'pizza-suwalki421.firebaseapp.com',
    storageBucket: 'pizza-suwalki421.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPripNNMrGgSmLdR49LEE_v45D6mm6HpY',
    appId: '1:967214662804:android:720ff79c4d6bae2f71e081',
    messagingSenderId: '967214662804',
    projectId: 'pizza-suwalki421',
    storageBucket: 'pizza-suwalki421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJfv4HOYnUH41wIBw3taCSMEf2fZIMtg',
    appId: '1:967214662804:ios:607028923080e41571e081',
    messagingSenderId: '967214662804',
    projectId: 'pizza-suwalki421',
    storageBucket: 'pizza-suwalki421.appspot.com',
    iosClientId: '967214662804-lco927nqijfm8rcku58e70qsmaei0t79.apps.googleusercontent.com',
    iosBundleId: 'com.klaudiabak.pizzaSuwalki',
  );
}
